// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnyzjttqixsnubmjwuba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBueXpqdHRxaXhzbnVibWp3dWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODE4NzgsImV4cCI6MjA1ODE1Nzg3OH0.LJH4PjT3s08a57FE0-7Wa3uOM3rhvjksn6rtbhMh2Vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);